import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "urban-glide-pro",
    name: "Urban Glide Pro",
    price: "$599",
    description: "Perfect for city commuting with a range of 25 miles.",
    image: "/image1.png",
    category: "urban",
    featured: true,
  },
  {
    id: "explorer-max",
    name: "Explorer Max",
    price: "$799",
    description: "Off-road capabilities with enhanced suspension.",
    image: "/image2.png",
    category: "offroad",
    featured: true,
  },
  {
    id: "commuter-elite",
    name: "Commuter Elite",
    price: "$499",
    originalPrice: "$599",
    description: "Lightweight and foldable for easy storage.",
    image: "/ter-1.png",
    category: "lightweight",
    featured: true,
  },
  {
    id: "speed-demon-x",
    name: "Speed Demon X",
    price: "$899",
    description: "High-speed performance with advanced safety features.",
    image: "/ter-2.png",
    category: "performance",
    featured: true,
  },
  {
    id: "city-cruiser",
    name: "City Cruiser",
    price: "$549",
    description: "Comfortable ride for urban environments with extended battery life.",
    image: "/ter-3.png",
    category: "urban",
  },
  {
    id: "trail-blazer",
    name: "Trail Blazer",
    price: "$849",
    description: "Designed for rough terrain with all-terrain tires and powerful motor.",
    image: "/ter-4.png",
    category: "offroad",
  },
  {
    id: "pocket-rocket",
    name: "Pocket Rocket",
    price: "$399",
    originalPrice: "$499",
    description: "Ultra-compact design that fits in any trunk or closet.",
    image: "/ter5.png",
    category: "lightweight",
  },
  // {
  //   id: "turbo-glider",
  //   name: "Turbo Glider",
  //   price: "$749",
  //   description: "Fast acceleration and top speeds for thrill-seekers.",
  //   image: "/placeholder.svg?height=300&width=300",
  //   category: "performance",
  // },
  // {
  //   id: "eco-rider",
  //   name: "Eco Rider",
  //   price: "$479",
  //   description: "Energy-efficient design with solar charging capabilities.",
  //   image: "/placeholder.svg?height=300&width=300",
  //   category: "urban",
  // },
  // {
  //   id: "mountain-master",
  //   name: "Mountain Master",
  //   price: "$899",
  //   description: "Conquer hills and mountains with powerful climbing abilities.",
  //   image: "/placeholder.svg?height=300&width=300",
  //   category: "offroad",
  // },
  // {
  //   id: "mini-glide",
  //   name: "Mini Glide",
  //   price: "$349",
  //   originalPrice: "$429",
  //   description: "Perfect for short trips and last-mile commuting.",
  //   image: "/placeholder.svg?height=300&width=300",
  //   category: "lightweight",
  // },
  // {
  //   id: "velocity-pro",
  //   name: "Velocity Pro",
  //   price: "$999",
  //   description: "Professional-grade scooter with top-of-the-line components.",
  //   image: "/placeholder.svg?height=300&width=300",
  //   category: "performance",
  // },
]

export const featuredProducts = products.filter((product) => product.featured)

